import { Driver } from "neo4j-driver";

/**
 * Generates Cypher commands for setting up unique key constraints and indexes for a given label in Neo4j.
 *
 * @param {string} label - The label for which the Cypher commands are generated.
 * @returns {Object} An object containing the Cypher commands:
 * - `dropIdCommand`: Command to drop the unique key constraint if it exists.
 * - `dropIndexCommand`: Command to drop the index if it exists.
 * - `createIdCommand`: Command to create the unique key constraint if it does not exist.
 */
const cypherSetupKeys = (label: string) => {
    const dropIdCommand = `
        DROP CONSTRAINT unique_key_${label}
        IF EXISTS;
    `
    const dropIndexCommand = `
        DROP INDEX key_index_${label} IF EXISTS;
    `
    const createIdCommand = `
        CREATE CONSTRAINT unique_key_${label}
        IF NOT EXISTS
        FOR (n:${label})
        REQUIRE n.key IS UNIQUE;
    `

    return {
        dropIdCommand,
        dropIndexCommand,
        createIdCommand,
}
}

/**
 * Sets up Neo4j keys for the specified labels.
 * 
 * This function takes a Neo4j driver and an array of labels, and for each label,
 * it runs a series of Cypher commands to drop existing indexes and IDs, and then
 * create new IDs. The commands are generated by the `cypherSetupKeys` function.
 * 
 * @param driver - The Neo4j driver instance used to create a session.
 * @param labels - An array of strings representing the labels for which the keys will be set up.
 * 
 * @returns A promise that resolves when all the commands have been executed and the session is closed.
 */
export const neoSetupKeys = async (driver: Driver, labels: string[]) => {
    // Start a new session with the Neo4j driver
    const session = driver.session()

    // Iterate over each label provided
    for (const label of labels) {
        // Generate the Cypher commands for the current label
        const {
            createIdCommand
        } = cypherSetupKeys(label)

        // Execute the command to create the unique key constraint if it does not exist
        await session.run(createIdCommand)
    }

    // Close the session after all commands have been executed
    await session.close()
}