name: tests

on:
  pull_request:
    branches:
    - main
    - master
    - dev
    - rc

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-and-linting:
    uses: ./.github/workflows/code-test.yaml

  docker-build:
    needs: tests-and-linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t image:test .
